#!/bin/bash
# Reduce design size by modifying RAM

echo "=========================================="
echo "Design Reduction Options"
echo "=========================================="
echo ""
echo "Current design: 202,574 instances (92.6% is RAM)"
echo "Target: < 100,000 instances"
echo ""
echo "Option 1: Reduce RAM from 2048x32 to 512x32 (减少75%)"
echo "  - Estimated instances: ~50,000"
echo "  - RAM size: 2KB (足够运行小程序)"
echo ""
echo "Option 2: Reduce RAM to 256x32 (减少87.5%)"
echo "  - Estimated instances: ~25,000"
echo "  - RAM size: 1KB"
echo ""
echo "Option 3: Remove RAM, use external memory only"
echo "  - Estimated instances: ~15,000"
echo "  - Requires external SDRAM/PSRAM"
echo ""
echo "Recommendation: Option 1 (512x32)"
echo ""
echo "To apply Option 1:"
echo "  1. Modify Chisel source to reduce RAM size"
echo "  2. Or manually edit ../build/ysyxSoCFull.v:"
echo "     - Change 'mem_2048x32' to 'mem_512x32'"
echo "     - Change 'Memory[0:2047]' to 'Memory[0:511]'"
echo "     - Change address width from [10:0] to [8:0]"
echo "  3. Re-run synthesis"
echo ""
echo "Quick fix (manual edit):"
echo "  sed -i 's/mem_2048x32/mem_512x32/g' ../build/ysyxSoCFull.v"
echo "  sed -i 's/Memory\[0:2047\]/Memory[0:511]/g' ../build/ysyxSoCFull.v"
echo "  sed -i 's/\[10:0\] R0_addr/[8:0] R0_addr/g' ../build/ysyxSoCFull.v"
echo "  sed -i 's/\[10:0\] W0_addr/[8:0] W0_addr/g' ../build/ysyxSoCFull.v"
echo "  sed -i 's/\[10:0\] _R0_addr_d0/[8:0] _R0_addr_d0/g' ../build/ysyxSoCFull.v"
echo ""
echo "=========================================="
